//
//  ContentCell.swift
//  Music-App
//
//  Created by Алексей Орловский on 11.05.2023.
//

import UIKit
import SnapKit

struct ContentCell {
    static let content = [
        Song(name: "Shootout (Sped Up)", image: UIImage(named: "track1.8")!, artistName: "Izzamuzzic, Julien Marchal", trackName: "song24", textMusic: "now This song has no lyrics"),
        Song(name: "У нее новый парень эй", image: UIImage(named: "track1.7")!, artistName: "teksidr", trackName: "song23", textMusic: "now This song has no lyrics"),
        Song(name: "METAMORPHOSIS 2", image: UIImage(named: "track")!, artistName: "INTERWORLD", trackName: "song1", textMusic: "I'ma pimp hoes fallin' for this pimpin' rap gameSlowly hit the tempo, just enough to keep these bitches tame Makin' fame off a nigga dick, bitches suckin' dick Make it quick, off my dick, yeah, I took a foreign chick Bankroll, other ho just a victim that I chose Have you suckin' 'til it's swole, I be bonin' other hoes Niggas wanna learn the game, but keep talkin' shit I'll be forced to trash 'em, may the best man win this"),
        Song(name: "End of line (but better)", image: UIImage(named: "track1.1")!, artistName: "rigergy", trackName: "song2", textMusic: "This song has no lyrics"),
        Song(name: "Polozhenie", image: UIImage(named: "track1.2")!, artistName: "Night lovell", trackName: "song3", textMusic: "Trippin′ on back from the last say summer Never tell a pack that I never stay runnin' Sippin′ on facts, damn know I got stacks In the lab takin' bitches straight for another cat Lace shit when I never had shit Bitch move, make your motherfuckin' head split Cost to the lost never really gon pay shit Tell me ain′t really gon chase it Dreams to the play, no fake Hands to the way, niggas know I ain′t play Fast to the brake when I switch all day Stans when I press to the dam all day Stickin' up signs, read never mind me Point to the ground, stake down to the v Stay, please stay, bitch you got no key Never take a seat, bitch you never gon′ see (gon' see)"),
        Song(name: "RAPTURE", image: UIImage(named: "track1.3")!, artistName: "INTERWORLD", trackName: "song4", textMusic: "Toe to toe Dancing very close Barely breathing Almost comatose Wall to wall People hypnotized And they're stepping lightly Hang each night in rapture Back to back Sacroiliac Spineless movement And a wild attack Face to face Sightless solitude And it's finger popping Twenty-four hour shopping in rapture Fab Five Freddy told me everybody's fly DJ spinnin' I said, My my Flash is fast, Flash is cool François c'est pas, Flash ain't no dude And you don't stop, sure shot Go out to the parking lot And you get in your car and drive real far And you drive all night and then you see a light And it comes right down and it lands on the ground And out comes a man from Mars And you try to run but he's got a gun And he shoots you dead and he eats your head And then you're in the man from Mars You go out at night eatin' cars You eat Cadillacs, Lincolns too Mercurys and Subaru And you don't stop, you keep on eatin' cars Then, when there's no more cars you go out at night And eat up bars where the people meet Face to face, dance cheek to cheek One to one, man to man Dance toe to toe, don't move too slow 'Cause the man from Mars is through with cars He's eatin' bars, yeah wall to wall Door to door, hall to hall He's gonna eat 'em all Rapture, be pure Take a tour through the sewer Don't strain your brain, paint a train You'll be singin' in the rain Said don't stop to punk rock Well now you see what you wanna be Just have your party on TV 'Cause the man from Mars won't eat up bars where the TV's on Now he's gone back up to space Where he won't have a hassle with the human race And you hip-hop, and you don't stop Just blast off, sure shot 'Cause the man from Mars stopped eatin' cars and eatin' bars And now he only eats guitars, get up"),
        Song(name: "METAMORPHOSIS", image: UIImage(named: "track1")!, artistName: "INTERWORLD", trackName: "song5", textMusic: "I'm a pimp, hoes fallin' for this pimpin' rap game Slowly hit the tempo, just enough to keep these bitches tame Makin' fame off a nigga dick, bitches suckin' dick Make it quick, off my dick, yeah, I took a foreign chick Bankroll other hoes, just a victim that I chose Have you suckin' 'til it's swole, I be bonin' other hoes Niggas wanna learn the game, but keep talkin' shit I'll be forced to trash 'em, may the best man win this I'm a pimp, hoes fallin' for this pimpin' rap game Slowly hit the tempo, just enough to keep these bitches tame Makin' fame off a nigga dick, bitches suckin' dick Make it quick, off my dick, yeah, I took a foreign chickBankroll other hoes, just a victim that I chose Have you suckin' 'til it's swole, I be bonin' other hoes Niggas wanna learn the game, but keep talkin' shit I'll be forced to trash 'em, may the best man win this"),
        Song(name: "On my own", image: UIImage(named: "track1.4")!, artistName: "Darci", trackName: "song20", textMusic: "No rush You just take your time Tell me I'm alright Take me through your mind Say I'm tryna fuck I think that you're right I still feel a thing when I look you in your eyes Maybe you're my weaknessOr just part of the season You know I've been speeding So maybe I just need this Or maybe I just feel you for no reason Maybe I just feel you for no reason (Yeah) No rush They say that I'm on a roll Maybe I just lost control These nights keep on taking tolls Find me out here on my own But I'm ending up with you home You keep picking up the bone Still I keep colder than stone 'Til you blowing up my phone Keeping with sexual tone When I wanna leave alone 'Til you blowing up my phone Keeping with sexual tone When I wanna leave alone (Yeah) They say that I'm on a roll Maybe I just lost control These nights keep on taking tolls Find me out here on my own You keep blowing up my phone Maybe I just lost control These nights keep on taking tolls On my On my On my own They say that I'm on a roll Lost control These nights keep on taking tolls Find me out here on my own You keep blowing up my phone Lost control These nights keep on taking tolls On my On my On my own No rush You just take your time Tell me I'm alright Take me through your mind Say I'm tryna fuck I think that you're right I still feel a thing when I look you in your eyes (Yeah) They say that I'm on a roll Maybe I just lost control These nights keep on taking tolls Find me out here on my own But I'm ending up with you home You keep picking up the bone Still I keep colder than stone 'Til you blowing up my phone On a roll Maybe I just lost control These nights keep on taking tolls Find me out here on my own You keep blowing up my phone Maybe I just lost control These nights keep on taking tolls On myOn my On my own They say that"),
        Song(name: "Help_urself", image: UIImage(named: "track1.5")!, artistName: "Ezekiel", trackName: "song21", textMusic: "This song has no lyrics"),
        Song(name: "Keraunos", image: UIImage(named: "track1.6")!, artistName: "PlayaPhonk", trackName: "song22", textMusic: "This song has no lyrics"),
        Song(name: "Close Eyes", image: UIImage(named: "track2")!, artistName: "Paradigma", trackName: "song6", textMusic: "This shit contagious Doin' dope This shit contagious Doin' dope DVRST (this shit contagious) Going through a thang but I gotta snapback Give it all to God, it's the pistol, put the crack back Stayin' on my job dealin' with haters with a jab step Dealin' with this mob, police watchin', studio phone tapped Going through a thang but I gotta snapback Give it all to God, it's the pistol, put the crack back Stayin' on my job dealin' with haters wiht a jab step Dealin' with this mob, police watchin', studio phone tapped You best believe that I could see you from a mile away Thought that my girl was down sleepin' with the enemy The streets are dangerous, I could be dead any day That's why I'm ridin' with my dawg smokin' plenty hay This shit contagious, doin' dope This shit contagious, doin' dope This shit contagious, doin' dope This shit contagious, doin' dope This shit contagious, doin' dope This shit contagious, doin' dope"),
        Song(name: "POOR", image: UIImage(named: "track3")!, artistName: "gqtis", trackName: "song7", textMusic: "Poor George, poor George Can't help he was born a King Poor George, poor George She said she wanted everything I'll show you mine, if you show me yours Look what you made me do Poor George, poor George He's going blind to watch you lose Takes a drag through the hole in his neck He's a Marlboro man Daddy said we could ride forever What's the back-up plan? Poor George They turn the light on, and it's burning up the sky Poor George You can kill him, but you'll never kill his pride Poor George Poor George Poor George"),
        Song(name: "NEON BLADE", image: UIImage(named: "track4")!, artistName: "Artworks", trackName: "song8", textMusic: "Pumpin' on some [?] hood jump chiefin' gotta get my high Scopin' out the murders mane it's time to do a driveby Pumpin' on some [?] hood jump chiefin' gotta get my high Scopin' out the murders mane it's timе to do a driveby Pumpin' on some [?] hood jump chiefin' gotta gеt my high Pumpin' on some [?] hood jump chiefin' gotta get my high Pumpin' on some [?] hood jump chiefin' gotta get my high Pumpin' on some [?] hood jump chiefin' gotta get my high"),
        Song(name: "Another One Bites The Dust", image: UIImage(named: "track5")!, artistName: "Queen", trackName: "song9", textMusic: "Let's go Steve walks warily down the street With his brim pulled way down lowAin't no sound but the sound of his feet Machine guns ready to go Are you ready hey are you ready for this? Are you hanging on the edge of your seat? cOut of the doorway the bullets rip To the sound of the beat yeah Another one bites the dust Another one bites the dust And another one gone and another one gone Another one bites the dust Hey I'm gonna get you too Another one bites the dust How do you think I'm going to get along Without you when you're gone You took me for everything that I had And kicked me out on my own Are you happy are you satisfied? How long can you stand the heat Out of the doorway the bullets rip To the sound of the beat look out"),
        Song(name: "Blast", image: UIImage(named: "track6")!, artistName: "Artworks", trackName: "song10", textMusic: "This song has no lyrics"),
        Song(name: "Komarovo (Phonk Remix)", image: UIImage(named: "track7")!, artistName: "DVRST", trackName: "song11", textMusic: "На недельку до второго я уеду в комарово Поглядеть отвыкшим глазом на балтийскую волну И на море буду разом кораблем и водолазом Сам себя найду в пучине, если часом затону На недельку, до второго, я уеду в комарово Сам себя найду в пучине, если часом затону На недельку, до второго, я уеду в комарово Где качается на дюнах шереметьевский баркасc И у вас в карельских скалах на общественных началах Если только захотите, будет личный водолаз На недельку, до второго, я уеду в комарово И у вас, в карельских скалах, будет личный водолаз На недельку до второго я уеду в комарово На воскресной электричке к вам на краешек земли Водолазы ищут клады, только кладов мне не надо Я за то, чтоб в синем море не тонули корабли На недельку, до второго, я уеду в комарово Я за то, чтоб в синем море не тонули корабли На недельку (на недельку), до второго (до второго) Я уеду (я уеду), в комарово (хо-хо-хо) Я за то (ха-ха-ха), чтоб в синем море (ха-ха-ха), не тонули (хо-хо-хо) корабли"),
        Song(name: "Tokyo Drift Phonk", image: UIImage(named: "track8")!, artistName: "Artworks", trackName: "song12", textMusic: "Прокачал балансировку И мой Mark идёт на взлёт Слили в сеть ориентировку Но никто нас не найдёт Рёв мотора, визг колодок Валим боком на трэп дом Мы легенды новой школы Процветаем с каждым днём"),
        Song(name: "Passion", image: UIImage(named: "track9")!, artistName: "Fledgir", trackName: "song13", textMusic: "Said I had to clear up my head But tonight, I think I lost the plot instead I said that I'd be cleared out by three To the walls, I know they listen to me The teachers always called it a shame They say I don't have passion the same As I did a few years before They don't see the light there anymore They call it sad, but they're the outside lookin' in I mean they can't understand when they all cope with everything And when I opened my heart, in front of my friends, finally It was not what I thought, 'cause they're not there anymore I called my dad, he told me, There's no room for me Down at the house that we had when we were living as a three Now that my family's gone, almost as far as I can see I think they love me I'm sure, but they're not there anymore (hey) (Nah, nah-nah-nah-nah) Where can I sleep tonight? (Nah, nah-nah-nah-nah)"),
        Song(name: "Thunderstruck", image: UIImage(named: "track10")!, artistName: "AC/DC", trackName: "song14", textMusic: "Thunder, thunder, thunder, thunderThunder, thunder, thunder, thunder Thunder, thunderI was caught In the middle of a railroad track (thunder)I looked 'roundAnd I knew there was no turning back (thunder) My mind AracedAnd I thought, what could I do? (Thunder)And I knewThere was no help, no help from you (thunder)Sound of the drums Beating in my heartThe thunder of gunsTore me apart You've beenThunderstruckRode down the highwayBroke the limit, we hit the townWent through to Texas, yeah, Texas, and we had some funWe met some girls Some dancers who gave a good timeBroke all the rulesPlayed all the fools Yeah, yeah, they, they, they blew our mindsAnd I was shaking at the kneesCould I come again, please? Yeah, them ladies were too kind You've been Thunderstruck, thunderstruck Yeah, yeah, yeah, thunderstruck Ooh, thunderstruck, yeah"),
        Song(name: "Ever Present", image: UIImage(named: "track11")!, artistName: "Alberto Pinton", trackName: "song15", textMusic: "Ever present help in time of need Lifter of burdens, You carry me Ever present help in time of need Raising the broken up to their feet Let Your goodness and mercy Refresh my soul, revive me Let every valley become a spring A door of hope in suffering Everlasting friend, You've won my trust You sing in the morning, And dance through the dusk Everlasting friend, You've won my trust Through fields of forgiveness, You've shown me love Let Your goodness and mercy Refresh my soul, revive me Let every valley become a spring A door of hope in suffering I will not be shaken, no, You set Your love on me I am not forsaken, no, You never leave I will not be shaken, no, You set Your love on me I will not be shaken, no, You set Your love on me I am not forsaken, no, You never leave I will not be shaken, no, You set Your love on me Let Your goodness and mercy Refresh my soul, revive me Let every valley become a spring A door of hope in suffering"),
        Song(name: "Highway to hell", image: UIImage(named: "track12")!, artistName: "AC/DC", trackName: "song16", textMusic: "Livin' easy Lovin' free Season ticket on a one way ride Askin' nothin' Leave me be Takin' everythin' in my stride Don't need reason Don't need rhyme Ain't nothin' that I'd rather do Goin' down Party time My friends are gonna be there too I'm on the highway to hell On the highway to hell Highway to hell I'm on the highway to hell No stop signs Speed limit Nobody's gonna slow me down Like a wheel Gonna spin it Hey satan Payin' my dues Playin' in a rockin' bandHey mummaLook at meI'm on the way to the promised landI'm on the highway tohell Highway to hell I'm on the highway to hell Highway to hell Don't stop me I'm on the highway to hell On the highway to hell Highway to hell I'm on the highway to hell (Highway to hell) I'm on the highway to hell (Highway to hell) highway to hell (Highway to hell) highway to hell (Highway to hell) And I'm goin' down All the way I'm on the highway to hell_"),
        Song(name: "The Perfect Phonk", image: UIImage(named: "track13")!, artistName: "uquix", trackName: "song17", textMusic: "Project Pat don't give a fuck Project Pat don't give a fuck Project Pat don't give a fuck Project Pat don't give a fuck Project Pat don't give a fuck Project Pat don't give a fuck Project Pat don't give a fuck Project Pat don't give a fuck Project Pat don't give a fuck Project Pat don't give a fuck Project Pat don't give a fuck"),
        Song(name: "The Ringer", image: UIImage(named: "track14")!, artistName: "Eminem", trackName: "song18", textMusic: "Yeah, yo I'm just gonna write down my first thoughts And see where this takes me Cause I feel like I wanna punch the world in the fuckin' face right now Yeah, let me explain just how to make greatness Straight out the gate, I'm 'bout to break you down Ain't no mistakes allowed, but make no mistake I'm 'bout To rape the alphabet, I may raise some brows If I press the issue just to get the anger out (brrr) Full magazine could take Staples out Savage, but ain't thinkin' 'bout no bank account But bitch I'm off the chain like Kala Brown Motherfucker, shut the fuck up when I'm talkin', lil' bitch I'm sorry, wait, what's your talent? Oh, critiquin' My talent? Oh, bitch, I don't know who the fuck y'all are To give a sub-par bar, even have an opinion or view You mention me, millio of views, attention in news I mention you, lose-lose for me, win-win for you"),
        Song(name: "Don't Take Your Love From Me", image: UIImage(named: "track15")!, artistName: "Grover Washington Jr.", trackName: "song19", textMusic: "Tear a star from out the sky and the sky feels blue Tear a petal from the rose and the rose weeps too Take your heart away from mine and mine will surely break My life is yours to take, so please keep the spark awake Would you take the wings from birds so that they can’t fly? Would you take the ocean’s roar and leave just a sigh? All this, your heart won’t let you do This is what I beg of you Don’t take your love from me All this, your heart won’t let you do This is what I beg of you Don’t take your love from me Don’t take your love from me"),
        
    ]
}

// Song(name: "On my own", image: UIImage(named: "track1.4")!, artistName: "Darci", trackName: "song20", textMusic: ""),
